### ISSUE TITLE
Problem ved clientside henting av eksternt bilde via URL

### ISSUE THREAD

**Issue by knut-egil** [Knowit-Objectnet/kodekalender_frontend#46]
Testa ut det å laste opp bilde nå ved bruk av ekstern bilde URL (commit 4f422e53be2ada262356f91294402193bd7b6c5f) og innså at det er ikke i alle tilfeller hvor det er mulig. Dette skjer nok på grunn av CORS konfigurasjoner hos ekstern bilde host.
![image](https://github.com/Knowit-Objectnet/kodekalender_frontend/assets/86576502/7c91edd2-9035-4d3e-be54-23322cfce9f3)

Kan foreslå en løsning (som dere muligens allerede har vurdert og kommet frem til at ikke er ønskelig?), det å laste opp URL'et til deres server som så henter bildedataen. Dette vil i hvertfall la oss komme oss rundt CORS problemet, siden det er noe nettleseren håndterer.

**Comment by Goddesen** [comment]
Jeg tror ikke vi skal gjøre noe med dette. Er mest for convenience å kunne sette URL slik, i verste fall kan du jo bare laste ned bildet selv og putte det i filvelgeren. Å skulle gjøre dette på server blir en stor del ekstra orkestrering (for ikke å snakke om utvidet angrepsflate) for ganske lite benefit.

Hvis noe så kunne kanskje feilmeldingen vært litt bedre, men vet ikke hvor mye mer tid vi gidder å investere der nå.
